---
title: "Bradford"
author: "Bracq, Raymond"
date: "05/05/2024"
output:
  html_notebook: 
    encoding: UTF-8
  pdf_document: default
  html_document:
    df_print: paged
    encoding: UTF-8
editor_options:
  markdown:
    wrap: 72
---

# Bradford {.tabset .tabset-fade}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
library(haven)#si t'as pas les packages il faut faire install.packages("nom du package") dans la console
library(tidyverse)
library(dplyr)
library(labelled)
library(survey)
library(arrow)
library(ggplot2)
library(xtable)
library(questionr)
```

```{r base, include = FALSE}
source("Base.R")
```

### Stats desc sur discris


```{r}
tb <- cprop(svytable(~ origine_tous_g2_rec + d_lieudisagr_d_rec, indiv_immig_pd))
xtable(tb)
```
On peut prendre Algérie, Maroc/TUnisie, Afique sahélienne, afrique guinéenne/centrale et autres pays d'Afrique
```{r}
indiv_immigre <- indiv_immigre %>%
  mutate(agenq_cat = ntile(agenq, 5)) %>% 
  mutate(duretotfrm_cat = ntile(durtotfrm, 5))
indiv_immig_pd <- svydesign(ids = indiv_immigre$ident, data = indiv_immigre, weights = indiv_immigre$poidsi)

```

```{r}
tb <- cprop(svytable(~ agenq_cat + d_lieudisagr_d_rec, indiv_immig_pd))
xtable(tb)
cprop(svytable(~ duretotfrm_cat + d_lieudisagr_d_rec, indiv_immig_pd))

```
2 premiers quintiles d'âge, 3, 4 et 5 pour duretotfrm

```{r}
cprop(svytable(~ l_quart_secu_rec + d_lieudisagr_d_rec, indiv_immig_pd))

```
```{r}
tb <- cprop(svytable(~ sexee_rec + d_lieudisagr_d_rec, indiv_immig_pd))
xtable(tb)
```

```{r}
indiv_immigre_brad <- indiv_immigre %>% 
  filter(origine_tous_g2_rec %in% c("Immigres d'Algerie", "Immigres du Maroc/Tunisie", "Immigres d'Afrique sahelienne", "Immigres d'Afrique guineenne/centrale","Immigres d'autres pays d'Afrique")) %>% 
  filter(agenq_cat %in% c("1", "2")) %>%  # Avant 40 ans
  filter(sexee_rec=="Masculin") %>% 
  filter(i_contri_rec == "Jamais") #610 qui représentent en pondéré 317398

indiv_immigre_brad_pd <- svydesign(ids = indiv_immigre_brad$ident, data = indiv_immigre_brad, weights = indiv_immigre_brad$poidsi)

```

```{r}
prop.table(svytable(~i_cnfpol_rec, indiv_immigre_brad_pd))
```

```{r}
indiv_immigre_nonbrad <- indiv_immigre %>% 
  filter(origine_tous_g2_rec %in% c("Immigres d'Algerie", "Immigres du Maroc/Tunisie", "Immigres d'Afrique sahelienne", "Immigres d'Afrique guineenne/centrale","Immigres d'autres pays d'Afrique")) %>% 
  filter(agenq_cat %in% c("1", "2")) %>%  # Avant 40 ans
  filter(sexee_rec=="Masculin") %>% 
  filter(i_contri_rec != "Jamais") #313 qui représentent en pondéré 173519

indiv_immigre_nonbrad_pd <- svydesign(ids = indiv_immigre_nonbrad$ident, data = indiv_immigre_nonbrad, weights = indiv_immigre_nonbrad$poidsi)
```

```{r}
prop.table(svytable(~i_cnfpol_rec, indiv_immigre_nonbrad_pd))
```

```{r}
prop.table(svytable(~i_cnfpol_rec, indiv_immig_pd))
```